name: Report and address a bug
description: Create a bug report for a product defect you would like to address yourself
title: "[Event Request]: "
labels: ["event-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this event request form. 

        ⚠️⚠️ BEFORE WE GET STARTED ⚠️⚠️
        Before you create a new issue, please check the following:
        🔎 Search existing issues to avoid creating duplicates.
  - type: textarea
    id: describe-the-request
    attributes:
      label: Describe the request
      description: A clear and concise description of what the event request is, which you want Microsoft to address
      placeholder: Describe the event you would like to request
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Explain why you need this request to be fulfilled. This will help Microsoft assess, if your request could get solved in other ways.
      placeholder: Additional context
    validations:
      required: true