name: Report and address a bug
description: Create a bug report for a product defect you would like to address yourself
title: "[Extensibility Enhancement]: "
labels: ["extensibility-enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this extensibility enhancement form. 

        ⚠️⚠️ BEFORE WE GET STARTED ⚠️⚠️
        Before you create a new issue, please check the following:
        🔎 Search existing issues to avoid creating duplicates.
  - type: textarea
    id: describe-the-enhancement
    attributes:
      label: Describe the enhancement
      description: A clear and concise description of what the extensibility enhancement is, which you want Microsoft to address
      placeholder: Describe the extensibility you would like to request
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Explain why you need this request to be fulfilled. This will help Microsoft assess, if your request could get solved in other ways.
      placeholder: Additional context
    validations:
      required: true