name: 'Create tag and sync to mirror'

on:
  workflow_run:
    workflows: [' CI/CD']
    types: [requested]
    branches: ['main', 'release/*']

defaults:
  run:
    shell: pwsh


jobs:
  CreateTag:
    if: github.repository == 'aholstrup1/AlAppExtensions'
    runs-on: ubuntu-latest
    steps:
     - name: Push latest changes to mirror
      id: Sync
      run : |
        # Print github context
        Write-Host "GITHUB_CONTEXT: $ENV:GITHUB_CONTEXT"

        # Print github event
        Write-Host "GITHUB_EVENT: $ENV:GITHUB_EVENT"

        # Print github event payload
        $ghEvent = Get-Content $env:GITHUB_EVENT_PATH -Encoding UTF8
        Write-Host "GITHUB_EVENT_PAYLOAD: $ghEvent"


      # TODO: What should the tag be? 
      - name: Create version tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Query all artifacts from the build workflow
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            if(!allArtifacts) {
              console.log(`Could not fetch artifacts from run ID ${context.payload.workflow_run.id}`)
              return;
            }

            // Determine the build number, based on the apps artifact name
            const appsArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name.match(/.*-Apps-.*/)
            })[0];

            if(!appsArtifact) {
              console.log(`Could not find apps artifact from run ID ${context.payload.workflow_run.id}`)
              return;
            }

            // The build number is after -Apps-
            const buildNumber = appsArtifact.name.replace(/.*-Apps-/, "")
            const tag = `refs/tags/builds/${buildNumber}`

            console.log(`Creating tag: ${tag}`)

            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: tag,
              sha: context.sha
            });
  
  SyncRepository:
    needs: [ CreateTag ]
    if: needs.CreateTag.result == 'Success' && github.repository == 'aholstrup1/AlAppExtensions'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout mirror
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_REF }}
        repository: ${{ secrets.MIRRORREPONAME }}
        token: ${{ secrets.SYNCREPOSITORYTOKEN }}
        fetch-depth: 0

    - name: Push latest changes to mirror
      id: Sync
      run : |
          Write-Host "Syncing commit $ENV:GITHUB_SHA by $ENV:GITHUB_ACTOR to $ENV:GITHUB_REF"
          $Branch = $ENV:GITHUB_REF -replace "refs/heads/"
          $UpstreamRepo = "https://github.com/$ENV:GITHUB_REPOSITORY"

          Write-Host "Adding upstream"
          git remote add upstream $UpstreamRepo

          git fetch --all --prune
          git pull upstream $Branch

          Write-Host "Pushing $Branch to origin"
          git push origin $Branch
          git push origin --tags