name: 'Create tag and sync to mirror'

on:
  workflow_run:
    workflows: [' CI/CD']
    types: [requested]
    branches: ['main', 'release/*']

defaults:
  run:
    shell: pwsh


jobs:
  CreateTag:
    if: github.repository == 'aholstrup1/AlAppExtensions'
    runs-on: ubuntu-latest
    env:
      HEAD_COMMIT: ${{ github.event.workflow_run.head_commit.id }}
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
          ref: ${{ env.HEAD_COMMIT }}
          fetch-depth: 0

     - name: Set build tag
       id: GetBuildVersion
       env: 
        WORKFLOW_RUN_NUMBER: ${{ github.event.workflow_run.run_number}}
       run : .\Build\Scripts\Set-BuildTag.ps1 -BuildNumber $ENV:WORKFLOW_RUN_NUMBER

  SyncRepository:
    needs: [ CreateTag ]
    if: needs.CreateTag.result == 'Success' && github.repository == 'aholstrup1/AlAppExtensions'
    runs-on: ubuntu-latest
    env:
      HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      HEAD_COMMIT: ${{ github.event.workflow_run.head_commit.id }}
    steps:
    - name: Checkout mirror
      uses: actions/checkout@v3
      with:
        ref: ${{ env.BRANCH }}
        repository: ${{ secrets.MIRRORREPONAME }}
        token: ${{ secrets.SYNCREPOSITORYTOKEN }}
        fetch-depth: 0

    - name: Push latest changes to mirror
      id: Sync
      run : |
          $Branch = $ENV:HEAD_BRANCH -replace "refs/heads/"
          Write-Host "Pushing commit $ENV:HEAD_COMMIT by $ENV:GITHUB_ACTOR to $Branch"
          
          Write-Host "Adding upstream"
          $UpstreamRepo = "https://github.com/$ENV:GITHUB_REPOSITORY"
          git remote add upstream $UpstreamRepo

          git fetch --all --prune
          git merge upstream $ENV:HEAD_COMMIT

          Write-Host "Pushing $Branch to origin"
          git push origin $Branch
          git push origin --tags
