name: 'Publish Nuget'

on:
  workflow_run:
    workflows: ['Build']
    types: [completed]
    branches: ["main"]

permissions:
  contents: read
  actions: read
  pull-requests: read
  checks: read

defaults:
  run:
    shell: powershell

jobs:
  Publish:
    if: always() && github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    runs-on: [ windows-latest ]
    name: Publish Nuget
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Pull Request Changes
        if: github.event_name == 'workflow_run'
        uses: actions/github-script@v6
        with:
          script: |
            var run_id = Number('${{ github.event.workflow_run.id }}');
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: run_id
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == 'Pull_Request_Files'
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip'
            });
            var fs = require('fs');
            fs.writeFileSync('.PullRequestChanges.zip', Buffer.from(download.data));
