name: 'Publish Nuget'

on:
  workflow_run:
    workflows: ['Build']
    types: [completed]
    branches: ["main"]

permissions:
  contents: read
  actions: read
  pull-requests: read
  checks: read

defaults:
  run:
    shell: powershell

jobs:
  Publish:
    if: always() && github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    runs-on: [ windows-latest ]
    name: Publish Nuget
    steps:
      
      - name: Download Pull Request Changes
        if: github.event_name == 'workflow_run'
        uses: actions/github-script@v6
        with:
          script: |
            var run_id = Number('${{ github.event.workflow_run.id }}');
            const bv_artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: run_id
            });

            console.log("::group::Downloading artifacts");
            const files = bv_artifacts.map(async function(artifact) {
              let download = await github.rest.actions.downloadArtifact({
                owner: repo_parts[0],
                repo: repo_parts[1],
                artifact_id: artifact.id,
                archive_format: 'zip',
              });
              return await fs.writeFile(
                `${process.env.GITHUB_WORKSPACE}/${artifact.name}.zip`,
                Buffer.from(download.data),
              );
            });
            await Promise.all(files);
            console.log("Artifacts downloaded");
            console.log("::endgroup::");

