name: 'Publish Nuget'

on:
  workflow_run:
    workflows: ['Build']
    types: [completed]
    branches: ["main"]

permissions:
  contents: read
  actions: read
  pull-requests: read
  checks: read

defaults:
  run:
    shell: powershell

jobs:
  Publish:
    if: always() && github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'
    runs-on: [ windows-latest ]
    name: Publish Nuget
    steps:
      
      - name: Download Pull Request Changes
        if: github.event_name == 'workflow_run'
        uses: actions/github-script@v6
        with:
          script: |
            const downloadArtifact = async (artifact) => {
            let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: 'zip'
            });
            let fs = require('fs');
            fs.writeFileSync(`${artifact.archive_download_url}/${artifact.name}`, Buffer.from(download.data));
            };


            var run_id = Number('${{ github.event.workflow_run.id }}');
            console.log(`Downloading artifacts from workflow run: ${run_id} ${context.repo.owner} ${context.repo.repo}`);

            var all_artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run_id,
            });

            console.log(all_artifacts.data.artifacts);
            console.log(`Found ${all_artifacts.data.total_count} artifacts`);

            for (const artifact of all_artifacts.data.artifacts) {
                const artifactFullName = `${artifact.archive_download_url}/${artifact.name}`;
                console.log(artifactFullName);
                try {
                    console.log(`Attempting to download artifact (${artifact.id}): ${artifactFullName}`);
                    await downloadArtifact(artifact);
                    console.log(`Successfully downloaded artifact (${artifact.id}): ${artifactFullName}`);
                    break;
                } catch (e) {
                    console.log(`Error while trying to download artifact (${artifact.id}): ${artifactFullName}. error: ${e}`);
                }
            }

            

