name: Sign Binaries

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

env:
  buildArtifactsPath: ${{ github.workspace }}/.artifacts
  buildScripts: ${{ github.workspace }}/Build/Scripts

jobs:
  Sign:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      #- name: Download Build Output
      #  env:
      #      GH_TOKEN: ${{ github.token }}
      #  run: |
      #      gh run download 4530221544 --pattern 'System Application-main-Apps-*' --dir $env:buildArtifactsPath
      
      - name: Install Azure SignTool
        run: |
          dotnet tool install --global AzureSignTool
      
      - name: Sign
        run: | 
          $Files = Get-ChildItem -Path $env:buildScripts -Filter CompileAppInBcContainer.ps1 -Recurse | Select-Object -ExpandProperty FullName | Select -First 1
          Write-Host "Signing files (1): $Files"
          $PathExists = Test-Path $Files
          Write-Host "PathExists (1): $PathExists"
          Build/Scripts/CodeSign.ps1 -Files $Files `
                                      -AzureKeyVaultURI "${{ secrets.KEY_VAULT_URL }}" `
                                      -AzureKeyVaultClientID "${{ secrets.KEY_VAULT_CLIENT_ID }}" `
                                      -AzureKeyVaultClientSecret "${{ secrets.KEY_VAULT_CLIENT_SECRET }}" `
                                      -AzureKeyVaultTenantID "${{ secrets.KEY_VAULT_TENANT_ID }}" `
                                      -AzureKeyVaultCertificateName "${{ secrets.KEY_VAULT_CERTIFICATE_NAME }}"

      - name: Upload Build Output
        uses: actions/upload-artifact@v2
        with:
          name: System Application (Signed)
          path: ${{ env.buildScripts }}

