name: 'Sync Mirror'

on:
  push:
    branches: [ 'main', 'release/*' ]

defaults:
  run:
    shell: pwsh


jobs:
  SyncRepository:
    if: github.repository_name == 'aholstrup1/AlAppExtensions'
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        id: log
        run : | 
          Write-Host "GITHUB_REF: $ENV:GITHUB_REF"
          Write-Host "GITHUB_SHA: $ENV:GITHUB_SHA"
          Write-Host "GITHUB_REPOSITORY: $ENV:GITHUB_REPOSITORY"
          Write-Host "GITHUB_ACTOR: $ENV:GITHUB_ACTOR"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}
          repository: ${{ secrets.MIRRORREPONAME }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Pull Changes from upstream
        id: Sync
        run : |
          $Branch = $ENV:GITHUB_REF -replace "refs/heads/"
          $UpstreamRepo = "https://github.com/$ENV:GITHUB_REPOSITORY"

          Write-Host "Adding upstream"
          git remote add upstream $UpstreamRepo

          git fetch --all --prune
          git pull upstream $Branch

          Write-Host "Pushing $Branch to origin"
          git push origin $Branch