name: 'Sync Mirror'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  packages: write

defaults:
  run:
    shell: powershell


jobs:
  GetBranches:
    runs-on: windows-latest
    steps:
      - name: Pull Changes from upstream
        id: Sync
        run : |
          git config --global user.email "aholstrup@microsoft.com"
          git config --global user.name "aholstrup1"

          git clone https://github.com/aholstrup1/ALAppExtensions.git
          cd ALAppExtensions
          git remote add upstream https://github.com/microsoft/AlAppExtensions

          git fetch
          git fetch upstream
          
          git checkout origin main
          git pull upstream aholstrup/main --allow-unrelated-histories
          git push origin main