name: 'Sync Mirror'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  packages: write

defaults:
  run:
    shell: powershell


jobs:
  GetBranches:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Changes from upstream
        id: Sync
        run : |
          $SourceBranch = "main"
          $TargetBranch = "main"
          Write-Host "SourceBranch: $SourceBranch"
          Write-Host "TargetBranch: $TargetBranch"
          git fetch --prune --unshallow

          $repo = "https://${{ secrets.GHTOKENWORKFLOW }}@github.com/microsoft/AlAppExtensions.git"
          git remote add mirror $repo
          git remote

          git checkout $TargetBranch
          git pull origin $TargetBranch

          git fetch mirror --prune --unshallow
          git pull mirror $SourceBranch

          git push