name: 'Sync Mirror'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  packages: write

defaults:
  run:
    shell: powershell


jobs:
  GetBranches:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: aholstrup1/AlAppExtensions-Mirror
          token: ${{ secrets.PAT }}

      - name: Pull Changes from upstream
        id: Sync
        run : |
          $Branch = "main"
          git config --global user.email "aholstrup@microsoft.com"
          git config --global user.name "aholstrup1"

          Write-Host "Adding upstream"
          $repo = "https://github.com/aholstrup1/ALAppExtensions.git"
          git remote add upstream $repo
          git remote

          git fetch --prune
          git fetch upstream --prune

          Write-Host "Checking out $Branch"

          git checkout $Branch
          git pull upstream $Branch

          Write-Host "Pushing $Branch to upstream"

          git push upstream $Branch