name: 'Sync Mirror'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  packages: write

defaults:
  run:
    shell: powershell


jobs:
  GetBranches:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Changes from upstream
        id: Sync
        run : |
          $SourceBranch = "main"
          $TargetBranch = "main"
          git config --global user.email "aholstrup@microsoft.com"
          git config --global user.name "aholstrup_microsoft"
          Write-Host "SourceBranch: $SourceBranch"
          Write-Host "TargetBranch: $TargetBranch"
          git fetch --prune

          Write-Host "Adding mirror remote"
          $repo = "https://${{ secrets.PAT }}@github.com/aholstrup_microsoft/AlAppExtensions-Mirror.git"
          git remote add mirror $repo
          git remote

          Write-Host "Checking out $TargetBranch"

          git checkout $TargetBranch
          git pull origin $TargetBranch

          Write-Host "Fetching $SourceBranch"

          git fetch mirror --prune
          git pull mirror $SourceBranch

          Write-Host "Pushing $TargetBranch to mirror"

          git push mirror $TargetBranch