name: Update Baseline Version

on:
  workflow_dispatch:
  schedule:
    - cron: "55 03 * * *" # Run at 03:55 UTC on Tuesday

defaults:
  run:
    shell: powershell

env:
  repoName: ${{ github.event.repository.name }}

jobs:
  UpdateBaseline:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update Baseline Version
        run: | 
          Build/Scripts/UpdateBaselineVersion.ps1 -Owner $env:GITHUB_REPOSITORY_OWNER -Repo $env:repoName -TargetBranch $env:GITHUB_REF_NAME -Token ${{ secrets.GHTOKENWORKFLOW }} -Actor $env:GITHUB_ACTOR
